import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import { ContentProvider } from "./context/ContentContext";
import TextArea from "./components/TextArea";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RSS Feed Content Creator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ContentProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <div className="flex mt-10 min-w-full justify-between">
            <Sidebar />
            <div className="pt-10 flex-4 flex-col md:flex-row justify-around">
              <h2 className="py-5 px-5 text-xl block mb-4 font-medium text-gray-900 dark:text-white">
                Here are your results 👇
              </h2>
              {children}
            </div>
            <TextArea />
          </div>
        </body>
      </html>
    </ContentProvider>
  );
}
